name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install youtube-dl
      run: |
        sudo wget -q https://yt-dl.org/downloads/latest/youtube-dl -O /usr/local/bin/youtube-dl
        sudo chmod a+rx /usr/local/bin/youtube-dl
    - name: Install ffmpeg
      run: sudo apt-get update && sudo apt-get install ffmpeg
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: Installing gems
      run: bundle install -j4
    - name: Sync updates
      run: bundle exec ruby update.rb
    - name: Generate landing page
      run: bundle exec ruby -r rss -S erb index.html.erb > index.html
