name: Update

on:
  push:
    branches: [ main ]
  schedule:
    - cron: 0 0 * * *

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install youtube-dl
      run: |
        sudo wget https://yt-dl.org/downloads/latest/youtube-dl -O /usr/local/bin/youtube-dl
        sudo chmod a+rx /usr/local/bin/youtube-dl
    - name: Install ffmpeg
      run: sudo apt-get install ffmpeg
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: Fetch updates
      run: ruby update.rb
    - name: Push updates
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git status
        git add feed.xml data/
        git commit -m "Updated $(date -u)" || exit 0
        git push
