name: Update

on:
  push:
    branches: [ action ]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
       lfs: true
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: Fetch updates
      run: ruby update.rb
    - name: Push updates
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git status
        git add feed.xml data/
        git commit -m "Updated $(date -u)" || exit 0
        git push
